// Tipo de observatorio según su origen y/o financiación
const types = [
  {
    key: 'publico',
    name: 'Público',
  },
  {
    key: 'hibrido',
    name: 'Público-privado',
  },
]

const scopes = [
  {
    key: 'estatal',
    name: 'Estatal',
  },
  {
    key: 'municipal',
    name: 'Municipal',
  },
  {
    key: 'andalucia',
    name: 'Andalucía',
  },
  {
    key: 'aragon',
    name: 'Aragón',
  },
  {
    key: 'asturias',
    name: 'Asturias',
  },
  {
    key: 'cantabria',
    name: 'Cantabria',
  },
  {
    key: 'castilla_la_mancha',
    name: 'Castilla-La Mancha',
  },
  {
    key: 'castilla_y_leon',
    name: 'Castilla y León',
  },
  {
    key: 'cataluna',
    name: 'Cataluña',
  },
  {
    key: 'extremadura',
    name: 'Extremadura',
  },
  {
    key: 'galicia',
    name: 'Galicia',
  },
  {
    key: 'islas_baleares',
    name: 'Islas Baleares',
  },
  {
    key: 'canarias',
    name: 'Canarias',
  },
  {
    key: 'la_rioja',
    name: 'la_rioja',
  },
  {
    key: 'comunidad_de_madrid',
    name: 'Comunidad de Madrid',
  },
  {
    key: 'region_de_murcia',
    name: 'Región de Murcia',
  },
  {
    key: 'navarra',
    name: 'Navarra',
  },
  {
    key: 'pais_vasco',
    name: 'País Vasco',
  },
  {
    key: 'comunidad_valenciana',
    name: 'Comunidad Valenciana',
  },
  {
    key: 'ceuta',
    name: 'Ceuta',
  },
  {
    key: 'melilla',
    name: 'Melilla',
  },
]

const observatories = [
  {
    id: '1',
    name: 'Observatorio contra el Fraude y la Corrupción Sanitaria',
    parents: ['Ministerio de Sanidad'],
    description: `<a
        href="https://twitter.com/Monica_Garcia_G/status/1768227454223565199"
        >Anunciado</a
      > en rueda de prensa por la ministra de Sanidad el 14 de marzo de 2024.`,
    scope: 'estatal',
    type: 'publico',
  },
  {
    id: '2',
    name: 'Observatorio de Salud de las Mujeres',
    parents: [
      'Ministerio de Sanidad',
      'Secretaría de Estado de Sanidad',
      'Dirección General de Salud Pública',
    ],
    description:
      'Para <q>la disminución de las desigualdades de género en salud, mediante la participación y colaboración entre el conjunto de agentes implicados, generando y difundiendo conocimiento que permita el análisis de género y promueva la inclusión del enfoque de género y la equidad en las políticas públicas de salud</q>.',
    website: 'https://www.observatoriosaludmujeres.es',
    scope: 'estatal',
    type: 'publico',
  },
  {
    id: '3',
    name: 'Observatorio del ferrocarril en España',
    parents: ['Ministerio de Transportes y Movilidad Sostenible'],
    docs: [
      {
        name: 'Informe 2022',
        url: 'https://cdn.transportes.gob.es/portal-web-transportes/ferroviario/observatorio/ofe_2022_feb2024_v3.3_prot.pdf',
      },
      {
        name: 'Informe 2021',
        url: 'https://cdn.mitma.gob.es/portal-web-drupal/ferroviario/observatorio/ofe_2021_feb2023_v2.pdf',
      },
      {
        name: 'Informe 2020',
        url: 'https://cdn.mitma.gob.es/portal-web-drupal/ferroviario/observatorio/ofe_2020.pdf',
      },
      {
        name: 'Informe 2019',
        url: 'https://cdn.mitma.gob.es/portal-web-drupal/ferroviario/observatorio/ofe_2019_mar2021.pdf',
      },
      {
        name: 'Informe 2018',
        url: 'https://cdn.mitma.gob.es/portal-web-drupal/ferroviario/observatorio/ofe2018_rev.pdf',
      },
    ],
    website:
      'https://www.transportes.gob.es/ferrocarriles/observatorios/observatorio-del-ferrocarril-en-espana',
    scope: 'estatal',
    type: 'publico',
  },
  {
    id: '4',
    name: "Observatori Municipal de l'Habitatge d'Alcoi",
    description:
      'Se <a href="https://www.omha.alcoi.org/wp-content/uploads/2022/03/TEXT-BOP-NUM-137-DE-220720-APROVACIO-DEFINITIVA.pdf">constituye el 22-07-2020</a>, y a fecha de marzo de 2024 solo se ha reunido en <a href="https://www.omha.alcoi.org/es/que-es-omha/">tres ocasiones</a>. Lamentablemente las actas de sus plenos no se pueden descargar. Tras las elecciones municipales de 2023, parece que el OMHA no ha tenido ninguna actividad.',
    url: 'https://www.omha.alcoi.org/',
    scope: 'municipal',
    from_date: '22-07-2020',
    location: 'Alcoy',
    type: 'publico',
    docs: [
      {
        name: 'Plan General de Ordenación Urbana',
        url: 'https://www.alcoi.org/export/sites/default/es/areas/urbanismo/transparencia/descargas_planeam/20200714-Normativa-Urbanistica-del-PGOU-completa.pdf',
      },
      {
        name: 'Que es el OMHA?',
        url: 'https://www.omha.alcoi.org/es/que-es-omha/',
      },
    ],
  },
  {
    id: '5',
    name: 'Observatorio Autonómico dos Ríos de Galicia',
  },
  {
    id: '6',
    name: 'Observatorio da Sociedade da Información e a Modernización de Galicia',
  },
  {
    id: '7',
    name: 'Observatorio da Violencia no Contorno Laboral',
  },
  {
    id: '8',
    name: 'Observatorio de Administración Electrónica',
  },
  {
    id: '9',
    name: 'Observatorio de Igualdad de Oportunidades entre Mujeres y Hombres',
    website:
      'https://www.inmujeres.gob.es/observatorios/observIgualdad/home.htm',
    type: 'publico',
    scope: 'estatal',
    parents: ['Ministerio de Igualdad', 'Instituto de las Mujeres'],
    docs: [
      {
        name: 'Real Decreto 1686/2000, de 6 de octubre, por el que se crea el Observatorio de la Igualdad de Oportunidades entre mujeres y hombres',
        url: 'https://www.inmujeres.gob.es/observatorios/observIgualdad/docs/realDecreto.pdf',
      },
    ],
  },
  {
    id: '10',
    name: 'Observatorio de la Imagen de las Mujeres',
    website: 'https://www.inmujeres.gob.es/observatorios/observImg/home.htm',
    type: 'publico',
    scope: 'estatal',
    parents: ['Ministerio de Igualdad', 'Instituto de las Mujeres'],
  },
  {
    id: '11',
    name: 'Observatorio de la Cadena Alimentaria',
    website:
      'https://www.mapa.gob.es/es/alimentacion/temas/observatorio-cadena/organizacion-y-estructura/',
    parents: [
      'Dirección General de la Industria Alimentaria',
      'Ministerio de Agricultura, Pesca y Alimentación',
    ],
    scope: 'estatal',
    type: 'publico',
  },
  {
    id: '12',
    name: 'Observatorio de la Ciencia Ciudadana',
  },
  {
    id: '13',
    name: 'Observatorio de la Gestión Empresarial en Biodiversidad',
  },
  {
    id: '14',
    name: 'Observatorio de la Infancia de España',
    website:
      'https://observatoriodelainfancia.mdsocialesa2030.gob.es/queEs/home.htm',
  },
  {
    id: '15',
    name: 'Observatorio de la Infancia de Andalucía',
  },
  {
    id: '16',
    name: 'Observatorio de la Infancia de Cataluña / Observatori dels Drets dels Infants',
  },
  {
    id: '17',
    name: 'Observatorio de la Infancia y la Adolescencia de Asturias',
  },
  {
    id: '18',
    name: 'Observatorio de Infancia del País Vasco',
    scope: 'pais_vasco',
  },
  {
    id: '19',
    name: 'Observatorio de Infancia de Cantabria',
  },
  {
    id: '20',
    name: 'Observatorio de la Infancia y la Adolescencia de les Illes Balears',
  },
  {
    id: '21',
    name: 'Observatorio de la Lectura y el Libro',
    parents: [
      'Ministerio de Cultura',
      'Dirección General del Libro y Fomento de la Lectura',
    ],
    type: 'publico',
    description:
      'Para <q>analizar permanentemente la situación del libro, la lectura y las bibliotecas en su conjunto, tal y como se establece en la disposición adicional segunda de la Ley 10/2007, de 22 de junio, de la Lectura, el Libro y las Bibliotecas</q>.',
    scope: 'estatal',
    docs: [
      {
        name: 'Real Decreto 1574/2007, de 30 de noviembre, por el que se regula el Observatorio de la Lectura y el Libro',
        url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2008-3',
      },
      {
        name: 'Ley 10/2007, de 22 de junio, de la lectura, del libro y de las bibliotecas',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-12351',
      },
    ],
    website:
      'https://www.cultura.gob.es/cultura/libro/observatorio-de-la-lectura-y-el-libro/que-es-el-observatorio.html',
  },
  {
    id: '22',
    name: 'Observatorio de la Realidad Social de Navarra',
    website: 'https://www.observatoriorealidadsocial.es/es/',
  },
  {
    id: '23',
    name: 'Observatorio de las Ocupaciones del Servicio Público de Empleo Estatal',
    website:
      'https://www.sepe.es/HomeSepe/que-es-el-sepe/comunicacion-institucional/publicaciones/publicaciones-oficiales/listado-pub-mercado-trabajo/observatorio-ocupaciones.html',
    email: 'observatorio.ocupacional@sepe.es',
    type: 'publico',
    scope: 'estatal',
  },
  {
    id: '24',
    name: 'Observatorio de Museos de España',
    website:
      'https://www.cultura.gob.es/observatorio-museos-espana/el-observatorio-de-museos-de-espana.html',
    parents: ['Ministerio de Cultura'],
    scope: 'estatal',
    type: 'publico',
    email: 'observatorio.museos@cultura.gob.es',
  },
  {
    id: '25',
    name: 'Observatorio de Precios y Mercados de la Junta de Andalucía',
    scope: 'andalucia',
  },
  {
    id: '26',
    name: 'Observatorio de Salud Pública de Cantabria',
    scope: 'cantabria',
    type: 'publico',
    description:
      'Su misión es <q>Generar información relevante y de calidad a políticos, gestores, investigadores, profesionales de la salud y a la sociedad civil en general con el fin de mejorar las políticas, programas y servicios sanitarios-sociosanitarios de forma que respondan equitativa y eficientemente a las necesidades de salud de la población y a la reducción de las desigualdades en salud en Cantabria</Q>.',
    parents: [
      'Consejería de Sanidad',
      'Gobierno de Cantabria',
      'Fundación Marques de Valdecilla',
    ],
    website:
      'https://fmvaldecilla.es/unidad/observatorio-de-salud-publica-de-cantabria/',
  },
  {
    id: '27',
    name: 'Observatorio de Salud y Cambio Climático',
    scope: 'estatal',
    parents: ['Ministerio de Ciencia e Innovación'],
    description:
      'Nace <q>como un órgano colegiado intersectorial para apoyar el análisis, diagnóstico, evaluación y seguimiento de los efectos de la emergencia climática en la salud, al tiempo que ofrece apoyo científico-técnico a las Administraciones públicas</q>.',
    docs: [
      {
        name: 'Nota de prensa de la creación',
        url: 'https://www.miteco.gob.es/content/dam/miteco/es/prensa/23.07.18%20El%20Gobierno%20aprueba%20la%20creaci%C3%B3n%20del%20Observatorio%20de%20Salud%20y%20Cambio%20Clim%C3%A1tico.pdf',
      },
    ],
  },
  {
    id: '28',
    name: 'Observatorio de Vivienda y Suelo',
    scope: 'estatal',
    parents: ['Ministerio de Transportes y Movilidad Sostenible'],
  },
  {
    id: '29',
    name: 'Observatorio Aragonés de la Juventud',
    website: 'https://www.aragon.es/-/presentacion-1',
    description:
      'Para <q>conocer la realidad de la juventud aragonesa desde un enfoque integral, con el fin de orientar las políticas de juventud adecuándolas a sus necesidades reales, así como plantear actuaciones eficaces dirigidas a dicho colectivo, lo que implica obtener información relevante, sistemática y actualizada, sobre la situación actual de los jóvenes aragoneses, así como su evolución a lo largo del tiempo y los principales factores que inciden en la misma</q>.',
    scope: 'aragon',
    parents: ['Instituto Aragonés de la Juventud'],
    type: 'publico',
    is_active: 'Sí',
    from_date: '25 de marzo de 2015',
    docs: [
      {
        name: 'Informe-IAJ-paginas-sinlogos.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/Informe-IAJ-paginas-sinlogos.pdf/d0078bfc-5a3e-b099-1b2b-fd9fd16230d9?t=1624345162241',
      },
      {
        name: 'estudio+poblaci%C3%B3n+joven+2017.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/estudio+poblaci%C3%B3n+joven+2017.pdf/6737909d-73a0-2108-54ed-f61681b78672?t=1564133166888',
      },
      {
        name: 'estudio+poblacion+joven+2015.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/estudio+poblacion+joven+2015.pdf/5b72de7a-57c9-4466-f583-df71f91ab852?t=1564133102597',
      },
      {
        name: 'estudio+poblacion+joven+2013.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/estudio+poblacion+joven+2013.pdf/50359e1c-6c93-d649-369e-2eef4c0f2e7c?t=1564132952115',
      },
      {
        name: 'informe+sobre+las+actividades+juveniles+2018.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/informe+sobre+las+actividades+juveniles+2018.pdf/56765c1f-76ab-cc90-f35d-446dc4089cca?t=1564133341013',
      },
      {
        name: 'Informe+final+%2B+anexo_nuevo+%281%29.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/Informe+final+%2B+anexo_nuevo+%281%29.pdf/263d9298-49c2-d118-464c-1be388dcff6b?t=1592307413095',
      },
      {
        name: 'estuido+vivienda+joven+teruel.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/estuido+vivienda+joven+teruel.pdf/729d9573-f3e7-8836-4ab1-df674df4dd5b?t=1564133522455',
      },
      {
        name: 'estudio+violencia+en+el+lenguaje.pdf',
        url: 'https://www.aragon.es/documents/20127/2555757/estudio+violencia+en+el+lenguaje.pdf/ffb47bb0-7e97-be8c-4bd8-8bfcc8214c72?t=1564133700506',
      },
    ],
  },
  {
    id: '30',
    name: 'Observatorio del Medio Ambiente Urbano',
  },
  {
    id: '31',
    name: 'Observatorio del Transporte y la Logística en España',
    website: 'https://otle.transportes.gob.es',
  },
  {
    id: '32',
    name: 'Observatorio do Sector Lácteo de Galicia',
    website:
      'https://fogga.xunta.gal/es/sector_lacteo/observatorio_del_sector_lacteo',
    scope: 'galicia',
    type: 'publico',
    docs: [
      {
        name: 'Creación en el DOG, 9 de abril de 2007',
        url: 'https://fogga.xunta.gal/sites/w_fogga/files/ficheiros/pdf/d_61_2007.pdf',
      },
    ],
  },
  {
    id: '33',
    name: 'Observatorio Español contra la LGBTfobia',
  },
  {
    id: '34',
    name: 'Observatorio Español de Acuicultura',
    website: 'https://www.mapa.gob.es/es/pesca/temas/acuicultura/observatorio/',
  },
  {
    id: '35',
    name: 'Observatorio Español de I+D+I (ICONO)',
  },
  {
    id: '36',
    name: 'Observatorio de Salud y Medio Ambiente de Andalucía',
    website: 'https://www.osman.es',
    scope: 'andalucia',
    type: 'publico',
    parents: ['Junta de Andalucía', 'Consejería de Salud y Consumo'],
  },
  {
    id: '37',
    name: 'Observatorio Español de la Economía Social',
    website: 'http://www.observatorioeconomiasocial.es',
    parents: [
      'Ministerio de Trabajo y Economía Social',
      'Instituto Universitario de Economía Social y Cooperativa',
      'Universidad de Valencia',
    ],
  },
  {
    id: '38',
    name: 'Observatorio Español de las Drogas y las Adicciones',
    type: 'publico',
    scope: 'estatal',
    parents: ['Ministerio de Sanidad'],
    website:
      'https://pnsd.sanidad.gob.es/profesionales/sistemasInformacion/home.htm',
  },
  {
    id: '39',
    name: 'Observatorio Español del Racismo y la Xenofobia',
    website: 'https://www.inclusion.gob.es/oberaxe/',
    parents: ['Ministerio de Inclusión, Seguridad Social y Migraciones'],
    type: 'publico',
    scope: 'estatal',
  },
  {
    id: '40',
    name: 'Observatorio Estatal de Condiciones de Trabajo',
    scope: 'estatal',
  },
  {
    id: '41',
    name: 'Observatorio Estatal de Familias',
    scope: 'estatal',
  },
  {
    id: '42',
    name: 'Observatorio Estatal de la Convivencia Escolar',
    scope: 'estatal',
    website:
      'https://www.educacionyfp.gob.es/mc/sgctie/convivencia-escolar/observatorio.html',
  },
  {
    id: '43',
    name: 'Observatorio Estatal de la Dependencia',
    scope: 'estatal',
  },
  {
    id: '44',
    name: 'Observatorio Estatal de la Discapacidad',
    scope: 'estatal',
  },
  {
    id: '45',
    name: 'Observatorio Estatal de los Servicios Deportivos a las Administraciones Públicas',
    scope: 'estatal',
  },
  {
    id: '46',
    name: 'Observatorio de la Comunidad de Castilla y León (Sección de Género)',
    website:
      'https://familia.jcyl.es/web/es/mujer/observatorio-comunidad-seccion-genero.html',
    type: 'publico',
    scope: 'castilla_y_leon',
  },
  {
    id: '47',
    name: 'Observatorio de la Convivencia Escolar',
    website:
      'https://www.educa.jcyl.es/convivenciaescolar/es/observatorio-convivencia-escolar',
    type: 'publico',
    scope: 'castilla_y_leon',
  },
  {
    id: '48',
    name: 'Observatorio TransfomAcción y ParticipAcción',
    website: 'https://www.observatoriotransformacion.com',
    type: 'publico',
    scope: 'castilla_y_leon',
  },
  {
    id: '49',
    name: 'Observatorio Regional de la Sociedad de la Información de Castilla y León (ORSI)',
    website:
      'https://www.aytoburgos.es/-/observatorio-regional-de-la-sociedad-de-la-informacion-de-castilla-y-leon-orsi-',
    type: 'publico',
    scope: 'castilla_y_leon',
  },
  {
    id: '50',
    name: 'Observatorio de Agresiones',
    website:
      'https://www.saludcastillayleon.es/profesionales/es/prevencion-riesgos-laborales/plan-integral-frente-agresiones/observatorio-agresiones',
    type: 'publico',
    scope: 'castilla_y_leon',
  },
  {
    id: '51',
    name: 'Observatorio Galego Contra a Discriminación por Orientación Sexual e Identidade de Xénero',
    scope: 'galicia',
  },
  {
    id: '52',
    name: 'Observatorio Galego da biodiversidade',
    scope: 'galicia',
  },
  {
    id: '53',
    name: 'Observatorio Galego da Violencia de Xénero',
    scope: 'galicia',
  },
  {
    id: '54',
    name: 'Observatorio Galego de Acción Voluntaria',
    scope: 'galicia',
  },
  {
    id: '55',
    name: 'Observatorio Galego de Convivencia Escolar',
    scope: 'galicia',
  },
  {
    id: '56',
    name: 'Observatorio Galego de Dinamización Demográfica',
    scope: 'galicia',
  },
  {
    id: '57',
    name: 'Observatorio Galego de Educación Ambiental',
    scope: 'galicia',
  },
  {
    id: '58',
    name: 'Observatorio Nacional 5G',
    parents: ['Ministerio de Economía'],
    scope: 'estatal',
    is_active: 'No',
  },
  {
    id: '59',
    name: 'Observatorio Nacional contra el Despoblamiento',
    scope: 'estatal',
    parents: ['Gobierno de Cantabria', 'Ayuntamiento de Valderredible'],
    description:
      'Iniciativa del Ayuntamiento de Valderredible con el Gobierno de Cantabria, presentada en 2021 y 2022. A fecha de la primavera de 2024 no consta que se haya puesto en marcha.',
    docs: [
      {
        name: 'Marcano valora de forma “muy positiva” la propuesta de crear en Valderredible un Observatorio Nacional y Centro de Iniciativas contra el despoblamiento',
        url: 'https://www.cantabria.es/web/gobierno/detalle/-/journal_content/56_INSTANCE_DETALLE/16413/14868508',
      },
      {
        name: 'Valderredible quiere acoger un Observatorio Nacional contra el despoblamiento rural',
        url: 'https://www.eldiario.es/cantabria/ultimas-noticias/valderredible-quiere-acoger-observatorio-nacional-despoblamiento-rural_1_8004681.html',
      },
      {
        name: 'El Plan de Dinamización de Valderredible desarrollará un plan de actuaciones con el apoyo del Gobierno para potenciar su desarrollo y sus valores patrimoniales',
        url: 'https://www.cantabria.es/web/comunicados/w/el-plan-de-dinamizaci%C3%B3n-de-valderredible-desarrollar%C3%A1-un-plan-de-actuaciones-con-el-apoyo-del-gobierno-para-potenciar-su-desarrollo-y-sus-valores-patrimoniales',
      },
    ],
    is_active: 'No',
  },
  {
    id: '60',
    name: 'Observatorio Vasco de la Cultura',
    website: 'https://www.euskadi.eus/observatorio-vasco-cultura/',
    email: 'kulturabehatokia@euskadi.eus',
    parents: [
      'Gobierno Vasco',
      'Departamento de Cultura y Política Lingüística',
      'Viceconsejería de Cultura',
      'Dirección de Promoción de la Cultura',
    ],
    scope: 'pais_vasco',
    type: 'publico',
    docs: [
      {
        name: 'Edición del libro en euskera 2022',
        url: 'https://www.euskadi.eus/2024/edicion-del-libro-en-euskera-2022/web01-a3kebarg/eu/',
      },
      {
        name: 'Comercio interior del libro en la CAE 2022',
        url: 'https://www.euskadi.eus/2024/comercio-interior-del-libro-en-la-cae-2022/web01-a3kebarg/eu/',
      },
      {
        name: 'Análisis de la programación cultural de la CAE. Año 2023',
        url: 'https://www.euskadi.eus/2023/analisis-de-la-programacion-cultural-de-la-cae-ano-2023/web01-a3kebarg/eu/',
      },
    ],
    from_date: '14/02/2006',
  },
  {
    id: '61',
    name: 'Observatorio Nacional de las Telecomunicaciones y de la Sociedad de la Información',
    scope: 'estatal',
  },
  {
    id: '62',
    name: 'Observatorio Nacional de Seguridad Vial',
    scope: 'estatal',
  },
  {
    id: '63',
    name: 'Observatorio Nacional de Sequías e Inundaciones',
    scope: 'estatal',
  },
  {
    id: '64',
    name: 'Observatorio Profesional del Instituto Nacional de las Cualificaciones',
  },
  {
    id: '65',
    name: 'Observatorio Tecnológico',
    website: 'http://educalab.es/intef/tecnologia/observatorio-tecnologico',
  },
  {
    id: '66',
    name: 'Observatorio Territorial de Andalucía',
    scope: 'andalucia',
  },
  {
    id: '67',
    name: 'Observatorio para la Cibersociedad',
    // Kaputt
  },
  {
    id: '68',
    name: 'Sociedad de la Información en Navarra',
    scope: 'navarra',
    // Kaputt ?
  },
  {
    id: '69',
    name: 'Observatorio de Prospectiva Tecnológica Industrial',
    website: 'http://www.opti.org',
  },
  {
    id: '70',
    name: 'Observatorio de formación en red Scopeo',
    website: 'https://scopeo.usal.es',
  },
  {
    id: '71',
    name: 'Observatorio Mujeres, Ciencia e Innovación',
  },
  {
    id: '72',
    name: 'Observatorio da Mobilidade de Terras de Galicia',
    scope: 'galicia',
  },
  {
    id: '73',
    name: 'Observatorio Galego da Xuventude',
    scope: 'galicia',
  },
  {
    id: '74',
    name: 'Observatorio Coruñés contra a LGTBIfobia',
  },
  {
    id: '75',
    name: 'Observatorio de costes de transportes de mercancías por carretera de Galicia',
    scope: 'galicia',
  },
  {
    id: '76',
    name: 'Observatorio Gallego de la Familia y de la Infancia',
    scope: 'galicia',
  },
  {
    id: '77',
    name: 'Observatorio da Vivenda de Galicia',
    scope: 'galicia',
  },
  {
    id: '78',
    name: 'Observatorio da Lingua Galega',
    scope: 'galicia',
  },
  {
    id: '79',
    name: 'Observatorio Argos de la Junta de Andalucía',
    scope: 'andalucia',
  },
  {
    id: '80',
    name: 'Observatorio del Mercado de Trabajo del Instituto Aragonés de Empleo',
    scope: 'aragon',
  },
  {
    id: '81',
    name: 'Observatorio del Mercado de Trabajo del Servicio Público de Empleo del Principado de Asturias',
    scope: 'asturias',
  },
  {
    id: '82',
    name: 'Observatorio del Trabajo del Servicio de Ocupación de las Illes Balears',
    scope: 'islas_baleares',
  },
  {
    id: '83',
    name: 'Observatorio de Empleo y Formación del Servicio Cántabro de Empleo',
    scope: 'cantabria',
  },
  {
    id: '84',
    name: 'Observatorio Canario del Empleo y la Formación Profesional',
    scope: 'canarias',
  },
  {
    id: '85',
    name: 'Observatorio Socioeconómico de la Provincia de Badajoz',
  },
  {
    id: '86',
    name: 'Observatorio del Sector TIC en Extremadura',
    scope: 'extremadura',
  },
  {
    id: '87',
    name: 'Observatorio de las Familias y la Infancia de Extremadura',
    scope: 'extremadura',
  },
  {
    id: '88',
    name: 'Observatorio para la Convivencia Escolar de Extremadura',
    scope: 'extremadura',
  },
  {
    id: '89',
    name: 'Observatorio de Prevención de Riesgos Laborales de la Comunidad Autónoma de la Región de Murcia',
    scope: 'region_de_murcia',
  },
  {
    id: '90',
    name: 'Observatorio de Turismo de Extremadura',
    scope: 'extremadura',
  },
  {
    id: '91',
    name: 'Observatorio Extremeño de la Cultura',
    scope: 'extremadura',
  },
  {
    id: '92',
    name: 'Observatorio de Responsabilidad Social de Extremadura',
    scope: 'extremadura',
  },
  {
    id: '93',
    name: 'Observatorio sobre Drogas de la Región de Murcia',
    scope: 'region_de_murcia',
  },
  {
    id: '94',
    name: 'Observatorio Urbano de A Coruña',
    parents: ['Concello de A Coruña'],
    website:
      'https://www.coruna.gal/encifras/es/observatorios-municipales/observatorio-urbano-de-a-coruna',
    scope: 'municipal',
    location: 'A Coruña',
  },
  {
    id: '95',
    name: 'Observatorio municipal de igualdade e diversidade',
    parents: ['Concello de A Coruña'],
    website: 'https://www.coruna.gal/igualdade/es/servicios/observatorio',
    scope: 'municipal',
    location: 'A Coruña',
  },
  {
    id: '96',
    name: 'Observatorio turístico de A Coruña',
    parents: ['Concello de A Coruña', 'Universidade da Coruña'],
    website: 'https://acorunaot.udc.es',
    scope: 'municipal',
    location: 'A Coruña',
  },
  {
    id: '97',
    name: 'Observatorio de Accesibilidad Web',
    type: 'publico',
    scope: 'estatal',
    website:
      'https://administracionelectronica.gob.es/pae_Home/pae_Estrategias/pae_Accesibilidad/pae_Observatorio_de_Accesibilidad.html',
    // https://www.discapnet.es/innovacion/observatorio-accesibilidad-tic
  },
  {
    id: '98',
    name: 'Observatorio de Innovación de Navarra',
    type: 'publico',
    scope: 'navarra',
    website: 'https://observatorioinnovacion.navarra.es/es/el-observatorio',
    docs: [
      {
        name: 'Memoria 2022',
        url: 'https://www.navarra.es/documents/18551208/23439727/Infografia-memoria-2022.pdf/263da2df-efcd-0054-3007-26d0c4a692f5?t=1677834556413',
      },
    ],
  },
  {
    id: '99',
    name: 'Observatorio de la Movilidad Metropolitana (OMM)',
    parents: [
      'Ministerio para la Transición Ecológica y el Reto Demográfico',
      'Vicepresidencia Tercera del Gobierno',
    ],
    type: 'publico',
    scope: 'estatal',
    website:
      'https://www.miteco.gob.es/es/calidad-y-evaluacion-ambiental/temas/movilidad/omm.html',
  },
  {
    id: '100',
    name: 'Observatorio Global del Español',
    parents: [
      'Ministerio de Asuntos Exteriores, Unión Europea y Cooperación',
      'Secretaría de Estado para Iberoamérica y el Caribe',
      'Secretaría de Estado de Digitalización e Inteligencia Artificial',
      'Dirección del Instituto Cervantes',
      'Comisionado Especial para la Alianza por la Nueva Economía de la Lengua',
      'Ministerio de Educación y Formación Profesional',
      'Ministerio de Política Territorial',
      'Ministerio de Cultura y Deporte',
      'Ministerio de Ciencia e Innovación',
      'Ministerio de Universidades',
      'Consejo de Gobierno de la Comunidad Autónoma de La Rioja',
    ],
    scope: 'estatal',
    type: 'publico',
    docs: [
      {
        name: 'Creación en el BOE, junio de 2022',
        url: 'https://www.boe.es/eli/es/rd/2022/06/07/431/con',
      },
      {
        name: 'Primera comisión ejecutiva, marzo de 2024',
        url: 'https://cervantes.org/es/sobre-nosotros/sala-prensa/notas-prensa/observatorio-global-espanol-materializa-su-puesta-marcha',
      },
    ],
    from_date: '2022-06',
    is_active: 'Sí',
  },
  {
    id: '101',
    name: 'Observatorio Permanente de la Inmigración (OPI)',
    website:
      'https://www.inclusion.gob.es/web/opi/estadisticas/observatorio_permanente_inmigracion',
    email: 'sgam@inclusion.gob.es',
    parents: [
      'Ministerio de Inclusión, Seguridad Social y Migraciones',
      'Secretaría de Estado de Migraciones',
      'Subdirección General de Análisis Migratorio',
    ],
    scope: 'estatal',
    type: 'publico',
    docs: [
      {
        name: 'Ciudadanos ucranianos en España con documentación de residencia en vigor',
        url: 'https://www.inclusion.gob.es/web/opi/estadisticas/catalogo/ucranianos',
      },
      {
        name: 'Menores no acompañados y jóvenes extutelados con autorización de residencia',
        url: 'https://www.inclusion.gob.es/web/opi/estadisticas/catalogo/Menores',
      },
    ],
  },
  {
    id: '102',
    name: 'Observatorio Estatal de Violencia sobre la Mujer',
    scope: 'estatal',
    website:
      'https://violenciagenero.igualdad.gob.es/instituciones/observatorioEstatal/home.htm',
    parents: [
      'Ministerio de Igualdad',
      'Secretaría de Estado de Igualdad y contra la Violencia de Género',
      'Delegación del Gobierno contra la Violencia de Género',
    ],
    docs: [
      {
        name: 'Informe Ejecutivo del XV Informe Anual del Observatorio Estatal de Violencia sobre la Mujer 2021',
        url: 'https://violenciagenero.igualdad.gob.es/violenciaEnCifras/observatorio/informesEjecutivos/informes/Informe_Ejecutivo_2021.htm',
      },
      {
        name: 'Informe del Grupo de Trabajo de Investigación sobre la Infancia Víctima de la Violencia de Género. Año 2011',
        url: 'https://violenciagenero.igualdad.gob.es/violenciaEnCifras/observatorio/gruposTrabajo/informes/informe2011.htm',
      },
      {
        name: 'XV Informe Anual del Observatorio Estatal de Violencia sobre la Mujer. Año 2021',
        url: 'https://violenciagenero.igualdad.gob.es/violenciaEnCifras/observatorio/informesAnuales/informes/XV_Informe_2021.htm',
      },
    ],
  },
  {
    id: '103',
    name: 'Observatorio Urbano de Alcalá de Henares',
    parents: ['Ayuntamiento de Alcalá de Henares'],
    website:
      'https://www.ayto-alcaladehenares.es/el-salon-de-plenos-acoge-el-acto-ejecutivo-del-plan-de-accion-de-la-agenda-urbana-de-alcala/',
    scope: 'municipal',
    location: 'Alcalá de Henares',
    type: 'publico',
  },
  {
    id: '104',
    name: 'Observatorio de violencia de género de Alcalá',
    parents: ['Ayuntamiento de Alcalá de Henares'],
    location: 'Alcalá de Henares',
    website:
      'https://www.ayto-alcaladehenares.es/el-observatorio-de-violencia-de-genero-de-alcala-ha-atendido-a-mas-de-1500-mujeres-desde-2004-2/',
    scope: 'municipal',
    type: 'publico',
  },
  {
    id: '105',
    name: 'Observatorio Sociodemográfico del Ayuntamiento de Alcalá de Henares',
    parents: ['Ayuntamiento de Alcalá de Henares'],
    location: 'Alcalá de Henares',
    website:
      'https://urbanismo.ayto-alcaladehenares.es/observatorio-sociodemografico-2/',
    scope: 'municipal',
    type: 'publico',
  },
  {
    id: '106',
    name: 'Observatorio Alcalá en cifras',
    parents: ['Ayuntamiento de Alcalá de Henares'],
    location: 'Alcalá de Henares',
    website:
      'https://www.ayto-alcaladehenares.es/presentacion-del-observatorio-urbano-alcala-en-cifras/',
    scope: 'municipal',
    type: 'publico',
  },
  {
    id: '107',
    name: 'Observatorio de Comercio del Gobierno Vasco',
    website: 'https://www.euskadi.eus/gobierno-vasco/observatorio-comercio',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '108',
    name: 'Observatorio Vasco del Emprendimiento',
    website: 'https://eeb-ove.eus/inicio/',
    twitter: '@eeb_ove',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '109',
    name: 'Observatorio Vasco de Vivienda',
    website: 'https://www.euskadi.eus/observatoriovivienda/',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '110',
    name: 'Observatorio Vasco del Juego',
    website: 'https://www.euskadi.eus/gobierno-vasco/observatorio-vasco-juego/',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '111',
    name: 'Observatorio de Periodismo Machista',
    website: 'https://periodismomachista.com/',
    twitter: '@pemachista',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '112',
    name: 'Observatorio Vasco sobre Acoso y Discriminación',
    website: 'https://www.observatoriovascosobreacoso.com/',
    twitter: '@ObservVascoAcos',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '113',
    name: 'Observatorio Vasco de la Juventud - Gobierno Vasco',
    website: 'https://www.gazteaukera.euskadi.eus/hasiera/',
    twitter: '@gaztebehatokia',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '114',
    name: 'Observatorio de Coyuntura Industrial',
    website:
      'https://www.irekia.euskadi.eus/es/tags/observatoriodecoyunturaindustrial?uid=5196',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '115',
    name: 'Observatorio Vasco de Inmigración',
    website: 'https://www.ikuspegi.eus/',
    twitter: '@ikuspegi_eus',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '116',
    name: 'Observatorio Vasco LGTBI+',
    website: 'https://lgtbi-behatokia.eus/',
    twitter: '@BehatokiaLGTBI',
    scope: 'pais_vasco',
    type: 'publico',
  },
  {
    id: '117',
    name: 'Observatorio para la Convivencia Escolar',
    website:
      'https://www.carm.es/web/pagina?IDCONTENIDO=5316&RASTRO=c792$m4001&IDTIPO=100',
    email: 'observatorio.convivencia@murciaeduca.es',
    parents: [
      'Subdirección General de Evaluación Educativa y Ordenación Académica',
      'Dirección General de Recursos Humanos, Planificación Educativa e Innovación',
      'Consejería de Educación, Formación Profesional y Empleo',
      'Gobierno de la Región de Murcia',
    ],
    scope: 'region_de_murcia',
    type: 'publico',
    docs: [
      {
        name: 'Informe 2022',
        url: 'https://www.carm.es/web/descarga?ARCHIVO=INFORME%20CONVIVENCIA%202022.pdf&ALIAS=ARCH&IDCONTENIDO=187826&IDTIPO=60&RASTRO=c792$m4001,5316,8320',
      },
      { name: 'Informe 2021' },
      { name: 'Informe 2020' },
      { name: 'Informe 2019' },
      { name: 'Informe 2018' },
      { name: 'Informe 2017' },
      { name: 'Informe 2016' },
      { name: 'Informe 2015' },
      { name: 'Informe 2014' },
      { name: 'Informe 2013' },
      { name: 'Informe 2012' },
      { name: 'Informe 2011' },
      { name: 'Informe 2010' },
      { name: 'Informe 2009' },
      { name: 'Informe 2008' },
      { name: 'Informe 2007' },
    ],
  },
  {
    id: '118',
    name: 'Observatorio de Prevención de Riesgos Laborales',
    website: 'https://www.carm.es/web/pagina?IDCONTENIDO=740&IDTIPO=140',
    parents: ['Gobierno de la Región de Murcia'],
    scope: 'region_de_murcia',
    type: 'publico',
  },
  {
    id: '119',
    name: 'Observatorio Ocupacional',
    website:
      'https://www.carm.es/web/pagina?IDCONTENIDO=227&IDTIPO=200&__PLANT_PERSONALIZADA=/JSP/CARM/carm2018/organigramas/plantillaDetalleOrganigrama.jsp&IDESTRUCTURAJERARQUICA=473&RASTRO=c77$m5782',
    parents: [
      'Dirección General del Servicio Regional de Empleo y Formación > Servicio Regional de Empleo y Formación > Organismo Autónomo > Consejería de Educación, Formación Profesional y Empleo > Comunidad Autónoma de la Región de Murcia',
    ],
    scope: 'region_de_murcia',
    type: 'publico',
    docs: [
      {
        name: 'Último mes publicado de 2024: Paro',
        url: 'https://www.sefcarm.es/web/servlet/descarga?ARCHIVO=Paro%20Febrero%202024.xlsx&ALIAS=ARCH&&IDCONTENIDO=189145',
      },
      {
        name: 'Último mes publicado de 2024: Contratos',
        url: 'https://www.sefcarm.es/web/servlet/descarga?ARCHIVO=Contratos%20Febrero%202024.xlsx&ALIAS=ARCH&&IDCONTENIDO=189144',
      },
    ],
  },
  {
    id: '120',
    name: 'Observatorio Virtual del Paisaje Mediterráneo',
    website:
      'https://www.carm.es/web/pagina?IDCONTENIDO=5137&IDTIPO=11&RASTRO=c374$m5828',
    scope: 'region_de_murcia',
    type: 'publico',
  },
  {
    id: '121',
    name: 'Observatorio Regional de la Discapacidad',
    website:
      'https://www.carm.es/web/pagina?IDCONTENIDO=5137&IDTIPO=11&RASTRO=c374$m5828',
    scope: 'region_de_murcia',
    type: 'publico',
  },
  {
    id: '122',
    name: 'Observatorio de la Calidad de los Servicios de la Comunidad Autónoma de la Región de Murcia',
    website:
      'https://transparencia.carm.es/-/observatorio-de-la-calidad-de-los-servicios#gsc.tab=0',
    scope: 'region_de_murcia',
    type: 'publico',
    docs: [
      {
        name: 'Acta 2022',
        url: 'https://transparencia.carm.es/wres/transparencia/doc/Organos-colegiados/observatorio_calidad/2022-07-18/20220718_ACTA_SESION_CONSTITUTIVA_OCS_C.pdf',
      },
    ],
  },
  {
    id: '123',
    name: 'Observatorio de Igualdad',
    website:
      'https://transparencia.carm.es/-/observatorio-de-igualdad#gsc.tab=0',
    scope: 'region_de_murcia',
    type: 'publico',
  },
  {
    id: '124',
    name: 'Observatorio Regional contra la Discriminación por Orientación Sexual e Identidad de Género',
    website:
      'https://transparencia.carm.es/-/observatorio-regional-contra-la-discriminacion-por-orientacion-sexual-e-identidad-de-genero-en-la-comunidad-autonoma-de-la-region-de-murcia#gsc.tab=0',
    scope: 'region_de_murcia',
    type: 'publico',
  },
  {
    id: '125',
    name: 'Observatori Agroalimentari de Preus',
    website:
      'https://agricultura.gencat.cat/ca/departament/estadistiques/observatori-agroalimentari-preus/',
    email: 'estudis_prospectiva.daam@gencat.cat',
    parents: ['Generalitat de Catalunya'],
    scope: 'cataluna',
    type: 'publico',
    is_active: 'Sí',
  },
  {
    id: '126',
    name: 'Observatorio contra la Violencia Doméstica y de Género',
    website:
      'https://www.poderjudicial.es/cgpj/es/Temas/Violencia-domestica-y-de-genero/El-Observatorio-contra-la-violencia-domestica-y-de-genero/',
    parents: [
      'Consejo General del Poder Judicial',
      'Ministerio de Justicia',
      'Ministerio de Sanidad',
      'Ministerio del Interior',
      'Fiscalía General del Estado',
      'Comunidades autónomas con competencias transferidas en Justicia',
      'Consejo General de la Abogacía Española',
      'Consejo General de Procuradores de España',
    ],
    description:
      'Es <q>un instrumento de análisis y de actuación que, en el ámbito de la Administración de la Justicia, promueve iniciativas y medidas dirigidas a erradicar el problema social de la violencia doméstica y de género</q>.',
    scope: 'estatal',
    docs: [
      {
        name: 'Convenio de creación del Observatorio',
        url: 'https://www.poderjudicial.es/stfls/CGPJ/OBSERVATORIO%20DE%20VIOLENCIA%20DOM%C3%89STICA/FICHERO/Convenio%20creaci%C3%B3n%20Observatorio.pdf',
      },
      {
        name: 'Folleto conmemorativo del 20 aniversario del Observatorio contra la Violencia Doméstica y de Género',
        url: 'https://www.poderjudicial.es/stfls/CGPJ/OBSERVATORIO%20DE%20VIOLENCIA%20DOM%C3%89STICA/FICHEROS/20221123%20Folleto%20conmemorativo%20del%2020%20aniversario%20del%20Observatorio%20contra%20la%20Violencia%20Dom%C3%A9stica.pdf',
      },
    ],
    type: 'publico',
    is_active: 'Sí',
    from_date: '2002',
  },
  {
    id: '127',
    scope: 'estatal',
    name: 'Observatorio de seguridad y eficiencia de las operaciones aéreas',
    parents: ['ENAIRE', 'Colegio Oficial de Pilotos de la Aviación Comercial'],
    from_date: '2019',
    docs: [
      {
        name: 'Resolución de 27 de junio de 2022, de la Entidad Pública Empresarial ENAIRE, por la que se publica el Convenio con el Colegio Oficial de Pilotos, para la operación del Observatorio de seguridad y eficiencia de las operaciones aéreas',
        url: 'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2022-13358',
      },
    ],
  },
  {
    id: '128',
    name: 'Observatorio Permanente del Mercado de los Servicios Portuarios',
    website: 'https://observatorio.puertos.es/Paginas/Observatorio.aspx',
    email: 'observatorio@puertos.es',
    parents: ['Puertos del Estado'],
    scope: 'estatal',
    type: 'publico',
    description:
      'Nace <q>para analizar las condiciones de competitividad en relación con los precios y calidad de los servicios portuarios, y acordar las variables de competitividad sobre las que establecer recomendaciones</q>.',
    from_date: '2012-12-11',
    is_active: 'Sí',
  },
  {
    id: '129',
    name: 'Observatorio de Salud Pública de Galicia',
    parents: ['Dirección General de Salud Pública', 'Xunta de Galicia'],
    email: 'Observatorio.SP@sergas.gal',
    website: 'https://observatoriosaudepublica.sergas.gal/es',
    scope: 'galicia',
    type: 'publico',
    description:
      'Para <q>generar, analizar, reunir, organizar y comunicar información relevante y de calidad en el ámbito de la salud pública de Galicia, con el objetivo de proporcionar información basada en la evidencia científica, y ponerla a disposición de profesionales de la salud, de personal investigador, así como de la sociedad en general</q>.',
    is_active: 'Sí',
  },
  {
    id: '130',
    name: 'Observatorio de la Sostenibilidad del Regadío',
    scope: 'estatal',
    type: 'publico',
    website:
      'https://www.mapa.gob.es/es/desarrollo-rural/temas/gestion-sostenible-regadios/regadio-espanya/default_1.2.2.aspx',
    docs: [
      {
        name: 'Real Decreto 854/2022, de 11 de octubre, por el que se crean la Mesa Nacional del Regadío y el Observatorio de la Sostenibilidad del Regadío',
        url: 'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2022-16583',
      },
    ],
    from_date: '2022-10-12',
    description:
      'Para <q>informar sobre la evolución de los principales indicadores relativos a la sostenibilidad económica, social y medioambiental de la agricultura de regadío en España</q>.',
  },
  {
    id: '131',
    name: 'Observatorio del flamenco',
    scope: 'andalucia',
    type: 'publico',
    website:
      'https://www.juntadeandalucia.es/cultura/flamenco/content/observatorio-del-flamenco',
    email: 'institutoandaluz.flamenco@juntadeandalucia.es',
    parents: [
      'Agencia Andaluza de Instituciones Culturales',
      'Instituto Andaluz del Flamenco',
      'Junta de Andalucía',
    ],
    from_date: '21 de marzo de 2007',
    description:
      'Para <q>la obtención y análisis sistemático de información y datos objetivos del sector necesario para conocer su historia, estructura, impacto económico y realidad actual del arte jondo, así como una herramienta para su evaluación</q>.',
  },
  {
    id: '132',
    name: 'Observatorio de Vivienda y Suelo',
    scope: 'cantabria',
    website: 'https://www.observatoriovivienda.cantabria.es',
    email: 'bobsvivi@cantabria.es',
    parents: [
      'Dirección General de Vivienda',
      'Consejería de Fomento, Ordenación del Territorio y Medio Ambiente',
      'Gobierno de Cantabria',
    ],
  },
  {
    id: '133',
    name: 'Observatorio Ocupacional de la Universidad Miguel Hernández',
    scope: 'comunidad_valenciana',
    parents: ['Universidad Miguel Hernández'],
    website: 'https://observatorio.umh.es/',
    email: 'observatorio@umh.es',
    description:
      'Para <q>aumentar el nivel de “empleabilidad” de nuestro estudiantado y colectivo <i>alumni</i></q>.',
  },
  {
    id: '134',
    name: 'Observatorio Tributario Andaluz',
    scope: 'local',
    location: 'Málaga',
    docs: [
      {
        name: 'Evolutivo Deuda 2018-2022 (ultimos 5 años)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Deuda-2018-2022-ultimos-5-anos.pdf',
      },
      {
        name: 'Evolutivo Ingresos tributarios (2018-2022)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Ingresos-tributarios-2018-2022.pdf',
      },
      {
        name: 'Evolutivo Ingresos tributarios (2017-2021)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Ingresos-tributarios-2017-2021.pdf',
      },
      {
        name: 'Evolutivo Deuda 2017-2021 (ultimos 5 años)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Deuda-2017-2021-ultimos-5-anos.pdf',
      },
      {
        name: 'Evolutivo Deuda 2016-2020 (ultimos 5 años)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Deuda-2016-2020-ultimos-5-anos.pdf',
      },
      {
        name: 'Evolutivo Ingresos tributarios (2016-2020)',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Ingresos-tributarios-2016-2020.pdf',
      },
      {
        name: 'Evolutivo Deuda 2015-2019',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Deuda-2015-2019.pdf',
      },
      {
        name: 'Evolutivo Deuda 2014-2018',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Deuda.pdf',
      },
      {
        name: 'Evolutivo Ingresos tributarios 2015-2019',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Ingresos-tributarios-2015-2019.pdf',
      },
      {
        name: 'Evolutivo Ingresos tributarios 2014-2018',
        url: 'https://ota.malaga.eu/export/sites/ota/.galleries/Elaboracion-propia-OTA/Evolutivo-Ingresos-tributarios.pdf',
      },
    ],
    parents: [
      'Ayuntamiento de Málaga',
      'Subdirección de Presupuestos, Control y Estudios',
    ],
    website: 'https://ota.malaga.eu',
    email: 'ota@malaga.eu',
    type: 'publico',
    description:
      'Para <q>Constituir un instrumento de transparencia orientado a la investigación de la tributación local, la financiación a través de transferencias de otras administraciones, y en general, cualquier información de naturaleza económica con incidencia en el ámbito de la Administración Municipal</q>.',
  },
  {
    id: '135',
    name: 'Observatorio Galego da Biomasa',
    scope: 'galicia',
    parents: ['Xunta de Galicia'],
    website: 'http://www.observatoriobiomasa.gal',
    type: 'publico',
    description:
      'Para <q>proporcionar información relacionada con el sector que facilite su conocimiento, potencial, alternativas de aplicación, principales indicadores de impacto y difusión de casos de éxito</q>.',
  },
  {
    id: '136',
    name: 'Observatorio Navarro de la Cultura',
    scope: 'navarra',
    website: 'https://www.culturanavarra.es/es/presentacion-8',
    email: 'cultura@navarra.es',
    parents: [
      'Dirección General de Cultura - Institución Príncipe de Viana',
      'Departamento de Cultura, Deporte y Juventud del Gobierno de Navarra',
    ],
    description: 'Profundizar <q>en el conocimiento sobre los sectores culturales y creativos, y sistematizar la información cuantitativa y cualitativa en el ámbito de la cultura y la creatividad en Navarra que ayude en la elaboración de las políticas culturales y la toma de decisiones, investigue en tendencias, conexiones con otros sectores, etc., identifique las buenas prácticas y experiencias que se desarrollan dentro y fuera de Navarra, y fomente el conocimiento de los públicos de la cultura y la creatividad</q>.',
    type: 'publico',
    is_active: 'Sí',
  },
  {
    id: '137',
    name: 'Observatorio de Precios de Canarias',
    scope: 'canarias',
    website: 'https://www.gobiernodecanarias.org/agp/sgt/temas/estadistica/CM-observatorio.html',
    parents: [
      'Gobierno de Canarias',
    ],
    type: 'publico',
  },
  {
    id: '138',
    name: 'Observatorio de Márgenes Empresariales',
    scope: 'estatal',
    website: 'https://www.bde.es/wbe/es/inicio/observatorio-margenes-empresariales/',
    email: 'cultura@navarra.es',
    docs: [
      {
        name: 'Objetivo del Observatorio y primer informe trimestral (Julio 2023)',
        url: 'https://www.bde.es/f/webbe/INF/MenuHorizontal/Observatorio_margenes_empresariales/20230703_OME_Briefing.pdf',
      },
      {
        name: 'Informe Trimestral 2023 T3',
        url: 'https://www.bde.es/f/webbe/INF/MenuHorizontal/Observatorio_margenes_empresariales/20231218_OME_T3.pdf',
      },
    ],
    parents: [
      'Ministerio de Asuntos Económicos y Transformación Digital (MINECO)',
      'Banco de España (BdE)',
      'Agencia Estatal de Administración Tributaria (AEAT)',
    ],
    description: 'El Observatorio de márgenes empresariales es un proyecto conjunto del Ministerio de Asuntos Económicos y Transformación Digital, el Banco de España y la Agencia Tributaria que tiene como objetivo disponer de información para el seguimiento y el análisis de los márgenes empresariales y de mejorar el conocimiento sobre su evolución y sus implicaciones para el conjunto de la economía.',
    type: 'publico',
    is_active: 'Sí',
    from_date: '2023-07-03',
  },
  {id:  139,
    name: 'Observatori Agroalimentari de Preus',
    website: 'https://agricultura.gencat.cat/ca/departament/estadistiques/observatori-agroalimentari-preus/',
    email: 'estudis_prospectiva.daam@gencat.cat',
    parents: ['Gencat'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  140,
    name: 'Observatorio Vasco de la Cultura',
    website: 'https://www.euskadi.eus/observatorio-vasco-cultura/',
    email: 'kulturabehatokia@euskadi.eus',
    parents: ['Gobierno Vasco','Cultura y Política Lingüística','Viceconsejería de Cultura','Dirección de Promoción de la Cultura'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name:'Edición del libro en euskera 2022:',url:'https://www.euskadi.eus/2024/edicion-del-libro-en-euskera-2022/web01-a3kebarg/eu/'}],
    from_date: '14/02/2006',
    is_active: 'Sí',
    },
    {id:  141,
    },
    {id:  142,
    },
    {id:  143,
    name: 'Observatorio de la Vida Militar',
    website: 'www.observatoriodelavidamilitar.es/',
    email: 'info@observatoriodelavidamilitar.es',
    scope: 'estatal',
    type: 'publico',
    from_date: '14 de enero de 2014.',
    is_active: 'Sí',
    },
    {id:  144,
    name: 'Observatorio del Comercio 4.0',
    website: 'https://comercio.gob.es/ComercioInterior/Observatorio/Paginas/default.aspx',
    email: 'sgfomon.sscc@mincotur.es',
    parents: ['Ministerio de Economía, Comercio y Empresa'],
    scope: 'estatal',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  145,
    name: 'Observatorio de la Nutrición y de Estudio de la Obesidad AESAN',
    website: 'https://www.aesan.gob.es/AECOSAN/web/nutricion/seccion/observatorio.htm',
    parents: ['Ministerio de Derechos Sociales, Consumo y Agenda 2030'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  146,
    name: 'Observatorio de uso de medicamentos',
    website: 'https://www.aemps.gob.es/medicamentos-de-uso-humano/observatorio-de-uso-de-medicamentos/',
    parents: ['Ministerio de Sanidad'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  147,
    name: 'Observatorio de la Muerte Digna',
    website: 'http://www.nafarroa.gob.es/home_es/Temas/Portal+de+la+Salud/Ciudadania/Me+cuido/Al+final+de+la+vida/Observatorio+de+la+Muerte+Digna/',
    parents: ['Gobierno de Navarra. Departamento de Salud'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  148,
    name: 'Observatorio de Precios de los Alimentos',
    website: 'https://www.mapa.gob.es/es/alimentacion/servicios/observatorio-de-precios-de-los-alimentos/estudios-e-informes/default.aspx',
    parents: ['Ministerio de Agricultura, Pesca y Alimentación'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  149,
    name: 'Observatorio de márgenes empresariales',
    website: 'https://sede.agenciatributaria.gob.es/Sede/estadisticas/observatorio-margenes-empresariales/observatorio-margenes-empresariales.html',
    parents: ['Es un proyecto conjunto del Ministerio de Asuntos Económicos y Transformación Digital, el Banco de España y la Agencia Estatal de Administración Tributaria'],
    scope: 'estatal',
    type: 'publico',
    comment: 'Dentro de este proyecto en esta web se ofrecen varias bases de datos, anuales y trimestrales, procedentes del Impuesto sobre Sociedades y de los modelos de IVA y retenciones sobre rendimientos del trabajo. La población objeto de estudio en cada año son todas aquellas empresas no financieras que tengan declaraciones de estos tres impuestos, con la única exclusión de empresas en actividades con un alto porcentaje de operaciones exentas a efectos del IVA.',
    is_active: 'Sí',
    },
    {id:  150,
    name: 'Observatorio militar para la igualdad entre mujeres y hombres en las Fuerzas Armadas',
    website: 'https://www.defensa.gob.es/ministerio/organigrama/subdef/omi/',
    email: 'omigualdad@oc.mde.es',
    parents: ['Ministerio de Defensa'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  151,
    name: 'Observatorio de la Cadena Alimentaria y de la Madera de Euskadi',
    website: 'https://behatoki.eus/',
    parents: ['Gobierno Vasco','Hazi'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  152,
    name: 'Observatorio de Salud Pública de Navarra',
    website: 'https://portalsalud.navarra.es/es/observatorio',
    email: 'oscn@navarra.es',
    parents: ['Gobierno de Navarra. Departamento de Salud'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  153,
    name: 'Observatorio Aragonés de la Sociedad de la Información (OASI)',
    website: 'https://www.aragon.es/-/estudios-1',
    email: 'oasi@aragon.es',
    parents: ['Gobierno de Aragón'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  154,
    name: 'Observatorio Fiscal de la Comunitat Valenciana',
    website: 'https://atv.gva.es/es/observatori-fiscal',
    parents: ['Agència Tributària Valenciana'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  155,
    name: 'Observatorio de la montaña de Aragón',
    website: 'https://observatoriomontanaragon.com/',
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  156,
    name: 'Observatorio del Hábitat y Segregación Urbana de la Comunitat Valenciana',
    website: 'https://habitatge.gva.es/es/web/vivienda-y-calidad-en-la-edificacion/observatori-de-l-habitat-i-segregacio-urbana-de-la-cv',
    parents: ['Generalitat Valenciana. Consellería de Servicios Sociales, Igualdad y Vivienda'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  157,
    name: 'Observatorio de la escuela rural de Aragón',
    website: 'https://educa.aragon.es/-/innovacion/observatorio-rural',
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  158,
    name: 'Observatorio Valenciano del Trabajo Decente',
    website: 'https://ceice.gva.es/va/web/dg-trabajo/observatori-valencia-del-treball-decent',
    parents: ['Generalitat Valenciana. Consellería de Educación, Universidades y Ocupación'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  159,
    name: 'Observatorio de precios de la Comunitat Valenciana',
    website: 'https://argos.gva.es/es/web/prospectiva/observatori',
    parents: ['Generalitat Valenciana'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  160,
    name: 'Observatorio Valenciano de la Cultura',
    website: 'https://ovc.gva.es/es/observatori',
    parents: ['Generalitat Valenciana. Consellería de Cultura y Deporte'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  161,
    name: 'Observatorio de Brecha Digital',
    website: 'https://brechadigital.gva.es/es',
    parents: ['Generalitat Valenciana. Consellería de Innovación, Industria, Comercio y Turismo'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  162,
    name: 'Observatorio para la Convivencia Escolar',
    website: 'https://ceice.gva.es/es/web/inclusioeducativa/observatori-per-a-la-convivencia',
    parents: ['Generalitat Valenciana. Conselleria de Educación, Universidades y Empleo'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  163,
    name: 'Observatorio valenciano para la igualdad de trato, la no discriminación y la prevención de los delitos de odio.',
    website: 'https://inclusio.gva.es/es/web/igualdad-diversidad/observatori-valencia-per-a-la-igualtat-de-trace-la-no-discriminacio-i-la-prevencio-dels-delictes-d-odi',
    parents: ['Generalitat Valenciana. Conselleria de Servicios Sociales, Igualdad y Vivienda'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  164,
    name: 'Observatorio de la IA',
    website: 'https://observatorioia.gva.es/es/',
    parents: ['Generalitat Valenciana. Conselleria de Innovación, Industria, Comercio y Turismo'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  165,
    name: 'Observatorio normativa electoral valenciana',
    website: 'https://cjusticia.gva.es/es/web/processos-electorals/observatori-electoral',
    parents: ['Generalitat Valenciana. Conselleria de Justicia e Interior'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  166,
    name: 'Observatorio de la Industria y de los sectores económicos valencianos',
    website: 'https://portalindustria.gva.es/es/observatorio-de-la-industria',
    parents: ['Generalitat Valenciana. Conselleria de Innovación, Industria, Comercio y Turismo'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  167,
    name: 'Observatorio Ciudadano del Agua de la Comunidad Valenciana',
    website: 'https://mediambient.gva.es/es/web/agua/novedades/-/asset_publisher/cYq5fnvdHYwT/content/observatorio-ciudadano-del-agua-de-la-comunitat-valenciana',
    parents: ['Generalitat Valenciana. Conselleria de Medio Ambiente, Agua, Infraestructuras y Territorio'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  168,
    name: 'https://www.comunidad.madrid/servicios/salud/observatorio-resultados-servicio-madrileno-salud',
    website: 'https://www.comunidad.madrid/servicios/salud/observatorio-resultados-servicio-madrileno-salud',
    parents: ['Comunidad de Madrid. Consejería de Sanidad'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  169,
    name: 'Observatorio de la Comunidad de Madrid de Víctimas del Delito',
    website: 'https://www.comunidad.madrid/transparencia/unidad-organizativa-responsable/observatorio-comunidad-madrid-victimas-del-delito',
    parents: ['Comunidad de Madrid. Consejería de Presidencia, Justicia y Administración Local'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  170,
    name: 'Observatorio Socioeconómico de la Marina Alta',
    website: 'https://observatorimarinaalta.org/',
    email: 'observatori@creama.org',
    parents: ['Creama (Consorcio para la Recuperación Económica','y de la Actividad de la Marina Alta, Ayuntamiento de Dénia y otros municipios de la comarca, Generalitat Valenciana, Ministerio de Trabajo y Economía Social'],
    scope: 'local',
    type: 'mixto',
    from_date: '2018',
    is_active: 'Sí',
    },
    {id:  171,
    name: 'Observatori de la Mort',
    website: 'https://observatorisalut.gencat.cat/ca/observatori_mort/index.html',
    parents: ['autonómico'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name:'Listado de documentos publicados: Documentos e informes'}],
    from_date: '3 de Septiembre de 2019',
    is_active: 'Sí',
    },
    {id:  172,
    name: 'Observatorio de Precios y Mercados de la Junta de Andalucía',
    website: 'https://www.juntadeandalucia.es/agriculturaypesca/observatorio',
    parents: ['Consejeria de Agricultura y Pesca de la Junta de Andalucia'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Informes de precios agrícolas y ganaderos'}],
    is_active: 'Sí',
    },
    {id:  173,
    name: 'Observatorio Canario de Empleo',
    website: 'https://obecan.es/',
    email: 'info@obecan.es',
    parents: ['Gobierno de Canarias - Consejería de empleo y asuntos sociales'],
    scope: 'autonómico',
    type: 'publico',
    comment: 'Decreto que anuncia su creación',
    from_date: 'Diciembre 1998',
    is_active: 'Sí',
    },
    {id:  174,
    name: 'Observatorio de residuos de Bizkaia',
    website: 'https://bizkaikohirihondakinenbehatokia.com/es/observatorio-de-residuos/',
    parents: ['Garbiker, empresa pública 100% perteneciente a la Diputación Foral de Bizkaia y adscrita al Departamento de Medio Natural y Agricultura.'],
    scope: 'provincial',
    type: 'publico',
    docs: [{name: 'Informe Anual del Observatorio de Residuos de Bizkaia 2022. En teoría, hay histórico hasta 2010:', url 'https://bizkaikohirihondakinenbehatokia.com/es/en-numeros/#historico'}],
    from_date: '2011',
    },
    {id:  175,
    name: 'Observatorio Canario de la Juventud',
    website: 'https://www.gobiernodecanarias.org/juventud/programas/observatorio-canario-de-la-juventud/',
    parents: ['Gobierno de Canarias - Dirección general de juventud'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'El último informe es de 2013'}],
    comment: 'Se entremezcla con la dirección general de juventud. No tiene un correo propio sino que remite a la dirección general',
    is_active: 'Sí',
    },
    {id:  176,
    name: 'Observatorio Aragonés del Arte en la Esfera Pública',
    website: 'https://oaaep.unizar.es/',
    parents: ['Universidad de Zaragoza'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  177,
    name: 'Observatorio Aragonés por la convivencia y contra el acoso escolar',
    website: 'https://educa.aragon.es/-/convivencia-web-basico-enlaces',
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  178,
    name: 'Observatorio Regional de la Violencia de Género',
    website: 'https://www.comunidad.madrid/transparencia/unidad-organizativa-responsable/observatorio-regional-violencia-genero',
    parents: ['Consejería de Presidencia, justicia y Administración Local'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  179,
    name: 'Observatorio Aragonés de Dinamización Demográfica y Poblacional',
    website: 'https://observatoriopoblacion.aragon.es/',
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  180,
    name: 'Observatorio de precios en consumo JCCM',
    website: 'https://consumo.castillalamancha.es/node/23956',
    parents: ['Consejería de Sanidad de Castilla La Mancha'],
    scope: 'autonómico',
    type: 'publico',
    docs: ['Análisis de tendencias de la evolución de precios por grupo de productos:','Evolución precios Periodo Navidad 2022 - Diciembre 2023 (105.45 KB)','Evolución precios aceites Navidad 2023 (73.39 KB)','Evolución precios Periodo Navidad 3 a 18 de diciembre (735.75 KB)','Evolución precios aceites Navidad 2023 (Actualización) (982.56 KB)','Evolución precios aceites provincias Navidad 2023 (2ª Actualización) (1007.26 KB)','Evolución precio medio aceites Navidad 2023 (2ª actualización) (435.16 KB)','Evolución precios tipos alimentos Navidad 2023 (2ª actualización) (753.17 KB)'],
    from_date: 'Febrero 2022',
    is_active: 'Sí',
    },
    {id:  181,
    name: 'OBSERVATORIO PRECIOS CADENA AGROALIMENTARIA CASTILLA LA MANCHA',
    website: 'https://www.castillalamancha.es/gobierno/agriaguaydesrur/estructura/dgalimentacion/titular/observatorio-precios-cadena-agroalimentaria',
    email: 'observatoriocadena@jccm.es',
    parents: ['Consejería de agricultura y ganadería de castilla la mancha'],
    scope: 'autonómico',
    type: 'publico',
    comment: 'No he sido capaz de encontrar ningún informe, te dejo por aqui la información que he podido encontrar.',
    from_date: 'Decreto 94/2021, de 21 de septiembre, por el que se crea el Observatorio de Precios de la Cadena Agroalimentaria de Castilla-La Mancha. (D.O.C.M nº 186 de 27 de septiembre de 2021)',
    is_active: 'Sí',
    },
    {id:  182,
    name: 'Observatorio de Seguridad y Eficiencia de las Operaciones Aéreas',
    website: 'https://www.google.com/search?q=Observatorio+de+Seguridad+y+Eficiencia+de+las+Operaciones+A%C3%A9reas',
    parents: ['estatal'],
    scope: 'estatal',
    type: 'publico',
    from_date: '2 de julio de 2019',
    },
    {id:  183,
    },
    {id:  184,
    },
    {id:  185,
    },
    {id:  186,
    },
    {id:  187,
    },
    {id:  188,
    },
    {id:  189,
    },
    {id:  190,
    },
    {id:  191,
    },
    {id:  192,
    },
    {id:  193,
    },
    {id:  194,
    name: 'Observatorio de Accesibilidad de Euskadi',
    website: 'https://isek.euskadi.eus/webisek00-isekquees/es/',
    email: 'accesibilidad@euskadi.eus',
    parents: ['autonómico'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'I PLAN DE ACCIÓN DE LA ESTRATEGIA DE ACCESIBILIDAD UNIVERSAL DE EUSKADI Informe anual de Evaluación 2022'}],
    from_date: '21 de julio de 2021',
    is_active: 'Sí',
    },
    {id:  195,
    },
    {id:  196,
    name: 'Observatorio Nacional de Agresiones',
    website: 'https://www.consejogeneralenfermeria.org/observatorio-nacional/observatorio-de-agresiones',
    scope: 'estatal',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  197,
    name: 'De la realidad social de Navarra / análisis y prospección de la realidad de Navarra',
    website: 'https://www.observatoriorealidadsocial.es/es/estudios/',
    parents: ['Servicios sociales , empleo y vivienda'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{url: 'https://www.observatoriorealidadsocial.es/es/estudios/evolucion-del-empleo-en-navarra-diciembre-2023-informe-mensual/es-590756/'}],
    from_date: 'Aproximadamente 2016 (primeros estudios publicados como observatorio)',
    is_active: 'Sí',
    },
    {id:  198,
    name: 'Observatorio Municipal para la Inclusión Social',
    website: 'https://observatoriosocial.malaga.eu',
    email: 'observatorio.social@malaga.eu',
    parents: ['Ayuntamiento de Málaga.'],
    scope: 'local',
    type: 'publico',
    docs: [{url: 'https://observatoriosocial.malaga.eu/publicaciones/'}],
    is_active: 'Sí',
    },
    {id:  199,
    name: 'Observatorio Municipal para la Inclusión Social',
    website: 'https://observatoriosocial.malaga.eu/',
    email: 'observatorio.social@malaga.eu',
    parents: ['Área de Derechos Sociales'],
    scope: 'local',
    type: 'publico',
    docs: ['https://observatoriosocial.malaga.eu/publicaciones/'],
    from_date: '2011',
    },
    {id:  200,
    name: 'Observatori de la Bretxa Digital',
    website: 'https://brechadigital.gva.es/',
    email: 'observatorio_dglbd@gva.es',
    parents: ['Generalitat Valenciana - Conselleria de Innovación, Industria, Comercio y Turismo'],
    scope: 'autonómico',
    type: 'publico',
    docs: ['2023 CUADERNO DIGITAL EN EL SECTOR AGRARIO','2023 GUIA BASICA PARA CREAR CONTENIDO ACCESIBLE EN LAS REDES SOCIALES','2023 GUIA BASICA DE DOCUMENTOS ACCESIBLES','2023 GUIA BASICA DE ACCESIBILIDAD WEB','2023 INVESTIGACION, TRANSFERENCIA Y COMUNICACION. ACCIONES Y RESULTADOS EN TORNO A BRECHA DIGITAL GENERACIONAL','...','https://brechadigital.gva.es/es/publicacions'],
    from_date: '18 de marzo de 2021, mediante el DECRETO 43/2021, de 18 de marzo, del Consell, de creación del Observatorio de Brecha Digital.',
    is_active: 'Sí',
    },
    {id:  201,
    name: 'Observatorio Tributario Andaluz',
    website: 'https://ota.malaga.eu/',
    email: 'ota@malaga.eu',
    parents: ['Ayuntamiento de Málaga.'],
    scope: 'local',
    type: 'publico',
    docs: [{url: 'https://ota.malaga.eu/informes/'}],
    is_active: 'Sí',
    },
    {id:  202,
    name: 'Observatorio de la participación ciudadana en Navarra',
    website: 'https://gobiernoabierto.navarra.es/es/participacion/enviar-aportacion/1587/observatorio-participacion-ciudadana-navarra',
    parents: ['Gobierno abierto..presidencia'],
    scope: 'autonómico',
    type: 'mixto',
    docs: [{name: 'No hay informes publicados solo un plan de impulso a la.actividas 2016/17.', url:'https://gobiernoabierto.navarra.es/es/participacion/1587/impulso-participacion-ciudadana-navarra-2016-2019'}],
    from_date: '2016',
    to_date: 'No parece tener actividad.',
    },
    {id:  203,
    name: 'Observatorio de la Violencia de Género',
    website: 'https://observatorioviolencia.org',
    email: 'observatorioviolencia@fundacionmujeres.es',
    scope: 'estatal',
    type: 'mixto',
    docs: [{url: 'https://observatorioviolencia.org/informes-e-investigaciones/'}],
    from_date: '2005',
    },
    {id:  204,
    name: 'Observatorio Turístico',
    website: 'https://visita.malaga.eu/profesional/es/observatorio-turistico',
    email: 'visita@malaga.eu',
    parents: ['El Ayuntamiento de Málaga, la Universidad de Málaga y el Área de Turismo de Málaga.'],
    scope: 'local',
    type: 'publico',
    docs: [{url: 'https://visita.malaga.eu/profesional/es/observatorio-turistico/informes'}],
    is_active: 'Sí',
    },
    {id:  205,
    name: 'Observatorio Nacional de Enfermería',
    website: 'https://www.consejogeneralenfermeria.org/observatorio-nacional',
    scope: 'estatal',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  206,
    name: 'Observatorio de la Movilidad Viaria de Málaga (MOVIMA)',
    website: 'https://movilidad.malaga.eu/es/lineas-de-trabajo/movima/',
    email: 'movilidad@malaga.eu',
    parents: ['Ayuntamiento de Málaga.'],
    scope: 'local',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  207,
    name: 'Observatorio Nacional de Enfermería Escolar',
    website: 'https://www.consejogeneralenfermeria.org/observatorio-nacional/observatorio-nacional-de-enfermeria-escolar',
    scope: 'estatal',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  208,
    name: 'Observatori d'IA per a l'Administració Pública',
    website: 'https://observatorioia.gva.es/',
    parents: ['Generalitat Valenciana - Conselleria d'Innovació, Indústria, Comerç i Turisme'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '9 de junio de 2023, según el DECRETO 85/2023, de 9 de junio, del Consell, de creación del Observatorio de la Inteligencia Artificial de la Comunitat Valenciana.',
    is_active: 'Sí',
    },
    {id:  209,
    name: 'Observatorio Permanente del Mercado de los Servicios Portuarios',
    website: 'https://observatorio.puertos.es/Paginas/Observatorio.aspx',
    email: 'observatorio@puertos.es',
    parents: ['Organismo Público Puertos del Estado'],
    scope: 'estatal',
    type: 'publico',
    from_date: '11-12-2012',
    is_active: 'Sí',
    },
    {id:  210,
    name: 'Observatori Socioambiental de Menorca',
    website: 'https://www.obsam.cat/',
    email: 'smn.obsam@cime.es',
    parents: ['Instituto Menorquín de Estudios'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  211,
    name: 'Observatori de preus de la Comunitat Valenciana',
    website: 'https://argos.gva.es/va/web/prospectiva/observatori',
    parents: ['Generalitat Valenciana - Consellería de Economía Sostenible, Sectores Productivos, Comercio y Trabajo'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  212,
    name: 'Observatorio Nacional de Medicamentos Peligrosos',
    website: 'https://www.consejogeneralenfermeria.org/observatorio-nacional/observatorio-nacional-de-medicamentos-peligrosos',
    scope: 'estatal',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  213,
    name: 'OBSERVATORIO DE PRECIOS DE LOS PRODUCTOS AGROALIMETARIOS DE LA COMUNITAT VALENCIANA',
    website: 'https://www.gva.es/es/inicio/atencion_ciudadano/buscadores/departamentos/detalle_departamentos?id_dept=14851',
    scope: 'autonómico',
    type: 'publico',
    from_date: '6 de octubre de 2006, según el DECRETO 150/2006, de 6 de octubre, del Consell, por el que se crea el Observatorio de Precios de los Productos Agroalimentarios de la Comunitat Valenciana.',
    is_active: 'Sí',
    },
    {id:  214,
    },
    {id:  215,
    name: 'Observatorio de Contratación Pública Responsable de Canarias',
    website: 'https://contratacionresponsablecanarias.org/',
    email: 'info@contratacionresponsablecanarias.org',
    parents: ['Dirección General de Derechos Sociales e Inmigración del Gobierno de Canarias a través del proyecto Integra Responsable'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '2023',
    },
    {id:  216,
    name: 'Observatori del Canvi Climàtic',
    website: 'https://climaienergia.com/observatori/',
    email: 'observatori@climaienergia.com',
    parents: ['Ayuntamiento de Valencia'],
    scope: 'local',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  217,
    name: 'Observatorio de la Muerte Digna y de las Comisiones de Mortalidad de las Áreas de Salud.',
    website: 'https://www.astursalud.es/noticias/-/noticias/omd',
    parents: ['https://sede.asturias.es/bopa-disposiciones?p_p_id=pa_sede_bopa_web_portlet_SedeBopaDispositionWeb&p_p_lifecycle=0&_pa_sede_bopa_web_portlet_SedeBopaDispositionWeb_mvcRenderCommandName=%2Fdisposition%2Fdetail&p_r_p_dispositionText=2020-06176&p_r_p_dispositionReference=2020-06176&p_r_p_dispositionDate=03%2F08%2F2020'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  218,
    name: 'Observatori de Civisme i Valors',
    website: 'https://dretssocials.gencat.cat/ca/ambits_tematics/civisme_i_valors/observatori/',
    parents: ['Departament de Drets Socials (Generalitat)'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Informe monogràfic 2021: Dimensió comunitària als barris de Catalunya'}],
    },
    {id:  219,
    name: 'Observatorio contra la LGTBIfobia de Castilla - La Mancha',
    website: 'https://observatoriolgtbiclm.com/',
    parents: ['Desconocido por el momento.'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Desconocido por el momento.'}],
    from_date: '7 de Septiembre de 2021 (07-09-2021)',
    is_active: 'Sí',
    },
    {id:  220,
    name: 'Observatori del Treball i Model Productiu',
    website: 'https://observatoritreball.gencat.cat/ca/inici',
    parents: ['Departament d'Empresa i Treball (Generalitat)'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{url: 'https://www.idescat.cat/pec/2017-2020/?id=020202&paae=2024'}],
    is_active: 'Sí',
    },
    {id:  221,
    name: 'Observatorio de Transformación y Participación de Castilla y León',
    website: 'https://www.observatoriotransformacion.com/',
    email: 'observatoriotransformacion@gmail.com',
    parents: ['Junta de Castilla y León'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  222,
    name: 'Observatori del Sistema de Salut de Catalunya',
    website: 'https://observatorisalut.gencat.cat/ca/inici',
    parents: ['Agència de Qualitat i Avaluació Sanitàries de Catalunya (Generalitat)'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  223,
    name: 'Observatorio de ferrocarril en España',
    },
    {id:  224,
    name: 'Observatori de la Mort',
    website: 'https://observatorisalut.gencat.cat/ca/observatori_mort/',
    parents: ['Departament de Salut (Generalitat)'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  225,
    name: 'Observatorio de Drogodependencias de Castilla - La Mancha',
    website: 'https://sanidad.castillalamancha.es/ciudadanos/observatorio-de-drogodependencias-clm/que-es-el-od',
    parents: ['Consejería de Sanidad de Castilla - La Mancha','Servicio de Salud de Castilla-La Mancha (SESCAM)'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Consejería de Sanidad de Castilla - La Mancha, Servicio de Salud de Castilla-La Mancha (SESCAM)'}],
    from_date: 'Desconocido.',
    is_active: 'Sí',
    },
    {id:  226,
    name: 'Observatorio del Mercado de Trabajo de Castilla - La Mancha',
    website: 'https://empleoyformacion.castillalamancha.es/observatorio',
    parents: ['Junta de Comunidades de Castilla - La Mancha','Oficina de Orientación, Formación y Empleo'],
    scope: 'autonómico',
    type: 'publico',
    from_date: 'Desconocido.',
    is_active: 'Sí',
    },
    {id:  227,
    name: 'Observatorio del Cambio',
    website: 'https://www.aytobadajoz.es/es/empleo/estudios-y-estadisticas/observatorio-del-cambio',
    email: 'paborrego@alumnos.unex.es',
    parents: ['Ayuntamiento de Badajoz'],
    scope: 'local',
    type: 'publico',
    docs: [{name: '(2015):'}],
    from_date: 'El Observatorio del Cambio inició su andadura entre los años 2003 y 2004, años en los que se celebraron 20 sesiones temáticas que abarcaron cuestiones relacionadas con diferentes sectores y materias específicas de la ciudad. Posteriormente, del 2009  al 2011 se llevaron a cabo 13 nuevas sesiones. Todas estas sesiones están recogidas en sus correspondientes actas.',
    to_date: 'El último informe es de 2015',
    },
    {id:  228,
    name: 'Observatorio de precios en consumo de Castilla - La Mancha',
    website: 'https://consumo.castillalamancha.es/node/23956',
    parents: ['Consejería de Sanidad de Castilla - La Mancha.'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  229,
    name: 'Observatori SmartCatalonia',
    website: 'https://observatori.smartcatalonia.gencat.cat/about',
    email: 'smartcatalonia@gencat.cat',
    parents: ['Administració Oberta de Catalunya (Generalitat)'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  230,
    name: 'Observatorio Regional de la Convivencia Escolar de Castilla - La Mancha',
    website: 'https://www.educa.jccm.es/educa-jccm/cm/educa_jccm/tkContent?idContent=62664&locale=en_UK&textOnly=false',
    parents: ['Junta de Comunidades de Castilla - La Mancha.'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '1 de abril de 2008
    1 de febrero de 2016',
    },
    {id:  231,
    name: 'Observatorio de Promoción Industrial de Castilla - La Mancha',
    website: 'NaN',
    parents: ['Junta de Comunidades de Castilla - La Mancha'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '30 de agosto de 2022 (30/08/2022)',
    is_active: 'Sí',
    },
    {id:  232,
    name: 'Observatorio sobre el BREXIT de Castilla - La Mancha',
    website: 'https://ipex.es/global-news/articulos-de-interes/observatorio-de-castilla-la-mancha-sobre-el-brexit/',
    parents: ['Junta de Comunidades de Castilla - La Mancha','Consejería de Economía, Empresas y Empleo de Castilla - La Mancha','IPEX'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  233,
    name: 'Observatorio de la Actividad Física (OBAFI) de Castilla - La Mancha',
    website: 'https://obafi.es/',
    parents: ['Junta de Comunidades de Castilla - La Mancha'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{url: 'https://obafi.es/informes-de-centro/',name: '(NO ACCESIBLES)'}],
    is_active: 'Sí',
    },
    {id:  234,
    },
    {id:  235,
    name: 'Observatorio de la Vivienda Colaborativa de Castilla - La Mancha',
    website: 'https://coacmto.com/observatorio-vivienda-colaborativa-toledo',
    parents: ['Empresa Municipal de Suelo y Vivienda de Toledo.','Colegio de Arquitectos de Castilla - La Mancha. Demarcación de Toledo.'],
    scope: 'autonómico',
    type: 'mixto',
    from_date: '8 de Mayo de 2023',
    is_active: 'Sí',
    },
    {id:  236,
    name: 'Observatorio de Plagas y Enfermedades Agrícolas de Castilla y León',
    website: 'https://plagas.itacyl.es/',
    email: 'observatorio.plagas@itacyl.es',
    parents: ['Junta de Castilla y León'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '2009',
    is_active: 'Sí',
    },
    {id:  237,
    name: 'Observatorio de Derechos Humanos para el Sáhara Occidental de Castilla - La Mancha',
    website: 'NaN',
    scope: 'autonómico',
    type: 'mixto',
    },
    {id:  238,
    name: 'Observatorio de la Emancipación Juvenil en España',
    website: 'https://www.observatorioemancipacion.org/la-emancipacion-juvenil-en-espana-datos-generales/',
    email: 'info@fepa18.org',
    parents: ['Gobierno de España','Ministerio de Derecho Sociales y Agenda 030'],
    scope: 'estatal',
    type: 'publico',
    docs: [{name: 'Parece que los últimos datos son de 2021 pero la página figura actualizada a 2024'}],
    is_active: 'Sí',
    },
    {id:  239,
    name: 'Observatorio de Servicios Sociales y Dependencia de Castilla - La Mancha',
    website: 'NaN',
    parents: ['Junta de Comunidades de Castilla - La Mancha'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  240,
    name: 'Observatorio de Digitalización en el sector agroalimentario',
    website: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2024-323',
    parents: ['Ministerio de Agricultura, Pesca y Alimentación'],
    scope: 'estatal',
    type: 'mixto',
    docs: [{url: 'https://www.mapa.gob.es/es/desarrollo-rural/temas/innovacion-medio-rural/estudio_3def_tcm30-655779.pdf'}],
    },
    {id:  241,
    name: 'Observatorio del Comercio de Castilla - La Mancha',
    website: 'https://comercio.castillalamancha.es/observatorio-comercio',
    parents: ['Junta de Comunidades de Castilla - La Mancha.','Consejería de Economía, Empresas y Empleo de Castilla - La Mancha.','Dirección General de Turismo, Comercio y Artesanía'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '29 de Junio de 2021',
    is_active: 'Sí',
    },
    {id:  242,
    name: 'OBSERVATORIO ANDALUZ DE VIOLENCIA DE GÉNERO',
    website: 'https://www.juntadeandalucia.es/institutodelamujer/index.php/2013-08-08-10-31-21/observatorio-andaluz-de-violencia-de-genero',
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  243,
    name: 'OBSERVATORIO ANDALUZ DE LA PUBLICIDAD  NO SEXISTA',
    website: 'https://www.juntadeandalucia.es/institutodelamujer/index.php/observatorio-andaluz-de-publicidad-no-sexista',
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  244,
    name: 'Observatorio de la Infancia y Adolescencia de Andalucía',
    website: 'https://www.observatoriodelainfancia.es/oia/esp/index.aspx',
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  245,
    name: 'OBSERVATORIO PARA LA CONVIVENCIA ESCOLAR EN ANDALUCÍA',
    website: 'https://www.juntadeandalucia.es/educacion/portals/web/convivencia-escolar/estructura-y-funcionamiento',
    email: 'convivenciaescolar.ced@juntadeandalucia.es',
    parents: ['Consejería de desarrollo educativo y formación profesional de la Junta de Andalucía'],
    scope: 'autonómico',
    type: 'publico',
    from_date: 'Febrero 2007 (BOJA Nº 25, 2-2-2007)',
    },
    {id:  246,
    name: 'Obervatorio de Contratación Pública (ObCP)',
    website: 'https://www.obcp.es/',
    parents: ['estatal'],
    scope: 'estatal',
    type: 'publico',
    from_date: 'Octubre de 2011',
    is_active: 'Sí',
    },
    {id:  247,
    name: 'Observatorio para la Convivencia Escolar en Andalucía',
    website: 'https://www.juntadeandalucia.es/educacion/portals/web/convivencia-escolar/estructura-y-funcionamiento',
    parents: ['Consejería de Desarrollo Educativo y Formación Profesional'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '2 de febrero 2007',
    },
    {id:  248,
    name: 'Observatorio CIBIM',
    website: 'https://cibim.transportes.gob.es/observatorio-cibim',
    parents: ['Ministerio de Transportes, Movilidad y Agenda Urbana'],
    scope: 'estatal',
    type: 'publico',
    docs: ['2023','Tercer trimestre - Informe nº23','Segundo trimestre - Informe nº22','Primer trimestre - Informe nº21','2022','Cuarto trimestre 2022 - Informe nº20','Tercer trimestre 2022 - Informe Nº19','Primer semestre 2022 - Informe Nº18','2021','Cuarto trimestre 2021 - Informe nº 17','Tercer trimestre 2021 - Informe nº 16','Segundo trimestre 2021 - Informe nº 15','Primer trimestre 2021 - Informe nº14','2020','Cuarto trimestre 2020 - Informe nº13','Tercer trimestre 2020 - Informe nº12','Segundo trimestre 2020 - Informe nº11','Primer trimestre 2020 - Informe nº10','2019','Cuarto trimestre 2019 - Informe nº 9','Tercer trimestre 2019 - Informe nº 8','Primer semestre 2019 - Informe nº 7','2018','Enero a diciembre 2018 - Informe nº6','Enero a septiembre 2018 - Informe nº5','Enero 2017 a junio 2018 - Informe nº4','Enero 2017 hasta marzo 2018 - Informe nº3','2017','Enero 2017 a diciembre 2017 - Informe nº2','Enero 2017 a septiembre 2017 - Informe nº1'],
    from_date: 'Mayo 2017',
    is_active: 'Sí',
    },
    {id:  249,
    name: 'observatorio territorial de navarra',
    website: 'https://www.nasuvinsa.es/es/servicios/lursarea/observatorio',
    parents: ['Nasuvinsa I(empresa publcia 100%) Y presidencia del gobierno de Navarra'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'No constan'}],
    from_date: '2017 .- Conforme al  Decreto Foral Legislativo 1/2017, de 26 de julio, por el que se aprueba el Texto Refundido de la Ley Foral de Ordenación del Territorio y Urbanismo.',
    to_date: 'no consta cese',
    },
    {id:  250,
    name: 'OBSERVATORIO DE SALUD PUBLICA DE NAVARRA',
    website: 'https://portalsalud.navarra.es/es/observatorio',
    parents: ['Deapartamento de Salud/Osasumbidea, Gobierno de Navarra'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Indicadores socioeconómicos .-  series estqdísticas', url:  'https://portalsalud.navarra.es/documents/11746728/14014754/Indicadores+Navarra+Sociodemograficos.pdf/edf990af-6ce2-b1f6-683a-379b5e19b719?t=1686728893883'},
    {name: 'Estilos de vida.',url: 'https://portalsalud.navarra.es/documents/11746728/14014754/Indicadores+Navarra+Estilos+de+Vida+2023.pdf/e3767ecc-b4e4-f78b-cae5-5e0fc812afdd?t=1678092313421'}],
    from_date: 'desconocido.',
    to_date: 'a dìa de hoy sigue funcionando. Publica algunas excel con datos hasta al menos 2023',
    is_active: 'Sí',
    },
    {id:  251,
    name: 'OBSERVATORIO DE TRANSFORMACION DIGITAL DE NAVARRA',
    website: 'https://observatoriotransformaciondigital.navarra.es/es/',
    email: 'https://observatoriotransformaciondigital.navarra.es/es/contacto',
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Publica datos de acceso a los diversos servicios digitales prestados por el gobierno de navara, como la carpeta de salud, la clave PIN, las habilidades telémáticas de los usuarios, etc ..'}],
    from_date: 'Se aprueba por D Foral 252/23 de 145 de noiemvvre',
    comment: 'https://www.lexnavarra.navarra.es/detalle.asp?r=56512',
    is_active: 'Sí',
    },
    {id:  252,
    name: 'OBSERVATORIO JOVEEN',
    website: 'https://www.juventudnavarra.es/es/observatorio-joven',
    parents: ['cONSEJO DE LA JUVENTUD'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Se crea y regula por la Orden Foral 116/2012, de 27 de marzo'}],
    from_date: '2012',
    to_date: 'no cesa',
    is_active: 'Sí',
    },
    {id:  253,
    name: 'OBSERVATORIO TURÍSTICO DE NAVARRA',
    website: 'https://turismoprofesional.navarra.es/es/observatorio-turistico',
    email: 'EN LA WEB',
    parents: ['departamento de turismo'],
    scope: 'autonómico',
    type: 'publico',
    docs: ['publica informes, estudios y directivas publicas sobre turismo en navarra  coomel modelo de integracion del turismo itinerante.- https://www.visitnavarra.es/documents/8257989/19042206/Ordenación+T.Itinerante-VD.pdf/123ae990-82b8-f299-4139-4e12333f9515?t=1662553688136'],
    from_date: '2023',
    is_active: 'Sí',
    },
    {id:  254,
    name: 'BANDA ANCHA DE NAVARRA',
    website: 'https://bandaancha.navarra.es/es/inicio',
    email: 'bandaanchanavarra@navarra.es',
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'NO PARECE QEU FACILITE inrmes sino que es un instrumento de desarrollo del plan director de banda ancha de navarra , recopilando información sobre la red, de forma que permita "identificar de manera preliminar las zonas que reúnen las condiciones para ser consideradas como elegibles en actuaciones según los términos de la normativa de ayudas de Estado"'}],
    from_date: '2023',
    is_active: 'Sí',
    },
    {id:  255,
    name: 'Observatorio de precios agrarios',
    website: 'https://www.larioja.org/agricultura/es/estadistica-agraria/observatorio-precios-agrarios',
    email: 'estadistica.agri@larioja.org',
    parents: ['Gobierno de la Rioja'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Publica uno por semana desde 2010'}],
    from_date: '2010',
    is_active: 'Sí',
    },
    {id:  256,
    name: 'Observatorio Económico de Melilla',
    website: 'https://elfarodemelilla.es/echa-a-andar-el-observatorio-economico-de-melilla/',
    parents: ['Consejería de Presidencia'],
    scope: 'autonómico',
    type: 'mixto',
    from_date: '11/12/2023',
    is_active: 'Sí',
    },
    {id:  257,
    name: 'Observatorio del pluralismo religioso en España',
    website: 'https://www.observatorioreligion.es/',
    parents: ['Fundación Pluralismo y Convivencia'],
    scope: 'estatal',
    type: 'publico',
    docs: [{name: 'La acción social de las confesiones minoritarias en España: mapa, prácticas y percepciones. Diciembre 23'}],
    from_date: '2011',
    is_active: 'Sí',
    },
    {id:  258,
    name: 'Observatori Català de l’Esport',
    website: 'https://inefc.gencat.cat/ca/inefc/projectes_institucionals/observatori-de-lesport/index.html',
    email: 'observatori@gencat.cat',
    scope: 'autonómico',
    type: 'publico',
    docs: [{url: 'https://inefc.gencat.cat/ca/inefc/projectes_institucionals/observatori-de-lesport/publicacions/projectes/arxivem-esport-temps-covid19/'}],
    is_active: 'Sí',
    },
    {id:  259,
    name: 'Observatori Català de la Joventut',
    website: 'https://dretssocials.gencat.cat/ca/ambits_tematics/joventut/observatori_catala_de_la_joventut/index.html',
    email: 'ocj.dretssocials@gencat.cat',
    parents: ['Agència Catalana de la Joventut'],
    scope: 'estatal',
    type: 'publico',
    },
    {id:  260,
    name: 'Observatorio da Lusofonía Valentín Paz Andrade',
    website: 'No',
    parents: ['Xunta de Galicia.'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '10/10/2023',
    is_active: 'Sí',
    },
    {id:  261,
    name: 'Observatorio da Industria Aeroespacial',
    website: 'https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/',
    parents: ['El Observatorio de la industria Aeroespacial es una iniciativa que se desarrolla en el marco de la Civil UAVs Initiative, promovida por la Xunta de Galicia a través da Vicepresidencia Primera y Consellería de Economía, Empleo e Innovación, y llevado a cabo por el Consorcio Aeronáutico Gallego.'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{'financiamento da I+D no sector dos UAVs','Análise da cadea de valor do sector aeroespacial','Instrumentos de apoio á internacionalización','Análise da evolución das empresas do sector aeronáutico e aeroespacial en Galicia','Informe das contas anuais do sector'}],
    is_active: 'Sí',
    },
    {id:  262,
    name: 'Observatorio da Eólica Mariña de Galicia',
    website: 'https://www.inega.gal/es/inega/puntos-de-encuentro-energeticos/observatorios',
    parents: ['Xunta de Galicia'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  263,
    name: 'Observatorio Galego da Biomasa',
    website: 'http://www.observatoriobiomasa.gal/',
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  264,
    name: 'Observatorio do Comercio de Galicia',
    website: 'No',
    parents: ['Adscrito a la dirección xeral competente en materia de comercio de la Xunta de Galicia'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '17/12/2010',
    },
    {id:  265,
    name: 'Observatorio do Solo Empresarial de Galicia',
    website: 'https://www.observatoriodosoloempresarial.gal',
    parents: ['Instituto Galego da vivenda e solo'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  266,
    name: 'OBSERVATORIO DE LA VIVIENDA Y EL SUELO DE CANTABRIA',
    website: 'https://www.observatoriovivienda.cantabria.es/',
    email: 'bobsvivi@cantabria.es',
    parents: ['Dirección General de Vivienda'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{url: 'https://www.observatoriovivienda.cantabria.es/informes-de-instituciones-observatorio'}],
    },
    {id:  267,
    name: 'Observatorio da Vivenda de Galicia',
    website: 'https://www.observatoriodavivenda.gal',
    email: 'https://www.observatoriodavivenda.gal/gl/contact',
    parents: ['Instituto Galego da Vivenda e solo'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Zonas tensionadas por municipios 2023'}],
    },
    {id:  268,
    name: 'Observatorio Andaluz de la Publicidad no sexista',
    website: 'https://www.juntadeandalucia.es/institutodelamujer/index.php/observatorio-andaluz-de-publicidad-no-sexista',
    parents: ['Junta de Andalucía'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{'"Estereotipos sexistas en la publicidad de juguetes: situación y evolución". Análisis de las campañas de Navidad 2020-2023. AUC (PDF)','"Código de autorregulación de la publicidad infantil de juguetes" (PDF)','"El Libro Blanco de la Influencia Responsable". iCmedia (PDF)','"Manual de tratamiento periodístico del deporte femenino y las mujeres deportistas". (PDF)','"Manual para un lenguaje administrativo no sexista". IAM (PDF)','"Un lenguaje neutral en cuanto al género". Parlamento Europeo (PDF)','"Lectura fácil y lenguaje no sexista". Plena Inclusión (PDF)','"Mujeres sin nombre. Presencia de la mujer en los medios de comunicación. 2023" (PDF)','"La violencia digital de género: Una realidad invisible". Observatorio Nacional de la Tecnología y Sociedad. Políticas públicas contra la violencia de género 2022 (PDF)','"Manual Práctico Comunicación e Imagen con Perspectiva de Género 2022" (PDF)','"Cuaderno Nº13 La salud de las mujeres en los medios, la publicidad y las redes sociales". IAM (PDF)','"Libertad para jugar. Guía para la elección de juguetes sin estereotipos sexistas". Ministerio de Consumo (PDF)','"Guía de buenas prácticas para impulsar la igualdad de la mujer en los medios audiovisuales y el adecuado tratamiento de la violencia de género”. Consejo Audiovisual de Andalucía y Plataforma de Reguladores del Sector Audiovisual de Iberoamérica (PDF)','"Violencia contra las mujeres y medios de comunicación”. Edición Ministerio de Igualdad','"Hola, tú a mí no me conoces". Diccionario visual sobre las mujeres del siglo XXI. Instituto de las Mujeres. Club de Creativos/as'}],
    is_active: 'Sí',
    },
    {id:  269,
    name: 'Observatorio de precios de la Comunitat Valenciana',
    website: 'https://argos.gva.es/es/web/prospectiva/observatori',
    parents: ['Consellería de Economía Sostenible, Sectores Productivos, Comercio y Trabajo de la Comunitat Valenciana'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: '11_noviembre_23.pdf'}],
    from_date: 'Abril de 2022',
    is_active: 'Sí',
    },
    {id:  270,
    name: 'Observatorio Municipal Galego',
    website: 'http://www.observatorioredlocalis.com/',
    email: 'infogen@uvigo.es',
    parents: ['Universidade de Vigo'],
    scope: 'autonómico',
    type: 'publico',
    is_active: 'Sí',
    },
    {id:  271,
    name: 'Observatorio Aragonés de la Juventud',
    website: 'https://www.aragon.es/-/presentacion-1#anchor1',
    parents: ['autonómico'],
    scope: 'autonómico',
    type: 'publico',
    from_date: '25 de marzo de 2015',
    is_active: 'Sí',
    },
    {id:  272,
    name: 'Observatorio de Literatura Infantil y Juvenil de Zaragoza',
    website: 'https://www.zaragoza.es/sede/portal/organizacion/gruposmunicipales/servicio/noticia/225698',
    email: 'observatoriolij@cmalasarmas.com',
    parents: ['Ayuntamiento de Zaragoza'],
    scope: 'local',
    type: 'publico',
    },
    {id:  273,
    name: 'Observatorio del Flamenco',
    website: 'https://www.juntadeandalucia.es/cultura/flamenco/content/observatorio-del-flamenco',
    email: 'institutoandaluz.flamenco@juntadeandalucia.es',
    parents: ['Agencia Andaluza de Instituciones Culturales,','Instituto Andaluz del Flamenco,','Junta de Andalucía'],
    scope: 'autonómico',
    type: 'publico',
    docs: [{name: 'Análisis de la evolución del vestuario teatral del Ballet Nacional de España en la estética y funcionalidad del lenguaje corporal,','El Mellizo y Silverio en el Cádiz finisecular,','El flamenco como Patrimonio Inmaterial,','Flamenco, antropología y derechos culturales,','Los festivales flamencos en el mundo: Ritos, rotos y retos'}],
    from_date: '21 de marzo de 2007',
    is_active: 'Sí',
    },
    {id:  274,
    name: 'Observatorio de la I+D+i de Canarias',
    website: 'https://www.obidic.es/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  275,
    name: 'Observatorio de la Energia de Canarias',
    website: 'https://www3.gobiernodecanarias.org/ceic/energia/oecan/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  276,
    name: 'Observatorio Canario de la Salud',
    website: 'https://www3.gobiernodecanarias.org/sanidad/scs/contenidoGenerico.jsp?idDocument=ba5d4671-60dc-11ed-9e04-cd68079ec7ca&idCarpeta=61e907e3-d473-11e9-9a19-e5198e027117',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  277,
    name: 'Observatorio Canario de Empleo',
    website: 'https://obecan.es/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  278,
    },
    {id:  279,
    name: 'Observatorio Turístico de Canarias',
    website: 'https://www.gobiernodecanarias.org/turismo/estadisticas_y_estudios/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  280,
    name: 'Observatorio Canario de las Telecomunicaciones y de la Sociedad de la Información',
    website: 'https://www.octsi.es/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  281,
    name: 'Observatorio Industrial de Canarias',
    website: 'https://oic.itccanarias.org/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  282,
    name: 'Observatorio de Precios de Canarias',
    website: 'https://www.gobiernodecanarias.org/agp/sgt/temas/estadistica/CM-observatorio.html',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  283,
    name: 'Observatorio de Contratación Pública Responsable de Canarias',
    website: 'https://contratacionresponsablecanarias.org/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  284,
    name: 'Observatorio Canario de la Juventud',
    website: 'https://www.gobiernodecanarias.org/juventud/programas/observatorio-canario-de-la-juventud/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  285,
    name: 'Observatorio Canario del Cambio Climático',
    website: 'https://www.gobiernodecanarias.org/medioambiente/organos/observatorio-canario-del-cambio-climatico/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  286,
    name: 'Observatorio Canario de la Economía Azul',
    website: 'https://www.gobiernodecanarias.org/economia/ocea/',
    parents: ['Gobierno de Canarias'],
    scope: 'autonómico',
    type: 'publico',
    },
    {id:  287,
    },
    {id:  288,
    },
    
]

export { observatories, types, scopes }
